version: "3" 
services: 
################################
#   Setup postgres container
################################

################################
#   Setup node container
################################

################################
#   Setup frontend container
################################
  weather-tracker-app:
    build:
      context: .
      dockerfile: Dockerfile 
    expose:
      - 4000
      #bind the local port 4000 to the containers port 3000
    ports: 
      - 4000:3000
    environment:
      - NODE_ENV=development
    env_file:
      - .env
    volumes:
      - '.:/usr/src/app'
