export const ITEMS_ARE_LOADING = 'ITEMS_ARE_LOADING';
export const ITEMS_FETCH_DATA_SUCCESS = 'ITEMS_FETCH_DATA_SUCCESS';
export const ITEMS_HAS_ERRORED = 'ITEMS_HAS_ERRORED';
export const QUERY_SEARCH = 'QUERY_SEARCH';
